### ISSUE TITLE
Change the api from get-all-feeds to get-all-syncs

### ISSUE THREAD

**Issue by hrithikwins** [branding-catalyst-pvt-ltd/vibrancy-backend-node.js#3]
In https://github.com/branding-catalyst-pvt-ltd/vibrancy/issues/30
variables were renamed, so now we need that the api should be get-all-syncs and the data should be in the format of 
`"syncs" : [] `
Instead of ` "feeds" : []`

**Comment by hrithikwins** [comment]
https://github.com/branding-catalyst-pvt-ltd/vibrancy-backend-node.js/blob/db393f47f0a7a3f4e0ec9ad16fd0043d0cda4387/src/modules/feed/product.routes.js#L17-L19

**Comment by hrithikwins** [comment]
This should be get-all-syncs

**Comment by hrithikwins** [comment]
https://github.com/branding-catalyst-pvt-ltd/vibrancy-backend-node.js/blob/db393f47f0a7a3f4e0ec9ad16fd0043d0cda4387/src/modules/feed/product.controller.js#L37

This should be "syncs" instead of "feeds"

**Comment by hrithikwins** [comment]
Make this all on new branch @theharshguptaflutter

**Comment by theharshguptaflutter** [comment]
ok checking

**Comment by theharshguptaflutter** [comment]
@hrithikwins  done
